"""add estimates.project_description

Revision ID: 02deb171e1ab
Revises: 3bb3e1a10279
Create Date: 2026-09-10 13:13:56.547349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02deb171e1ab'
down_revision: Union[str, None] = '3bb3e1a10279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimates', sa.Column('project_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimates', 'project_description')
    # ### end Alembic commands ###
