"""add estimates.client_phone

Revision ID: 31b7a3ebc4ee
Revises: 02deb171e1ab
Create Date: 2026-09-11 09:17:43.356597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b7a3ebc4ee'
down_revision: Union[str, None] = '02deb171e1ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimates', sa.Column('client_phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimates', 'client_phone')
    # ### end Alembic commands ###
