"""add project deployment fields

Revision ID: 3618b418db65
Revises: 31b7a3ebc4ee
Create Date: 2026-09-15 12:42:05.569409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3618b418db65'
down_revision: Union[str, None] = '31b7a3ebc4ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('last_deploy_commit_sha', sa.String(length=40), nullable=True))
    op.add_column('projects', sa.Column('last_deploy_status', sa.String(length=20), nullable=True))
    op.add_column('projects', sa.Column('last_deployed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    # Not autogenerated — Alembic's default autogenerate doesn't detect new
    # CheckConstraints on existing tables, only ones present at table creation.
    op.create_check_constraint(
        'ck_projects_last_deploy_status_valid',
        'projects',
        "last_deploy_status IS NULL OR last_deploy_status IN ('PENDING', 'SUCCESS', 'FAILED')",
    )


def downgrade() -> None:
    op.drop_constraint('ck_projects_last_deploy_status_valid', 'projects', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'last_deployed_at')
    op.drop_column('projects', 'last_deploy_status')
    op.drop_column('projects', 'last_deploy_commit_sha')
    # ### end Alembic commands ###
