"""add github/jira sync fields, ad-hoc invoices

Revision ID: 3beba6d2b7a6
Revises: e90e0a659dc5
Create Date: 2026-09-17 11:30:45.136015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3beba6d2b7a6'
down_revision: Union[str, None] = 'e90e0a659dc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('invoices', 'milestone_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('projects', sa.Column('latest_commit_sha', sa.String(length=40), nullable=True))
    op.add_column('projects', sa.Column('latest_commit_message', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('latest_commit_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('projects', sa.Column('jira_project_key', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('jira_issue_count', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('jira_done_count', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('jira_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'jira_synced_at')
    op.drop_column('projects', 'jira_done_count')
    op.drop_column('projects', 'jira_issue_count')
    op.drop_column('projects', 'jira_project_key')
    op.drop_column('projects', 'latest_commit_synced_at')
    op.drop_column('projects', 'latest_commit_message')
    op.drop_column('projects', 'latest_commit_sha')
    op.alter_column('invoices', 'milestone_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('invoices', 'description')
    # ### end Alembic commands ###
