"""drop clerk_user_id

Revision ID: 43d631b0c32d
Revises: 60e61e70f18a
Create Date: 2026-09-15 14:02:58.523222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d631b0c32d'
down_revision: Union[str, None] = '60e61e70f18a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_clerk_user_id_key', 'users', type_='unique')
    op.drop_column('users', 'clerk_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_clerk_user_id_key', 'users', ['clerk_user_id'])
    # ### end Alembic commands ###
