"""add invoices, project updates, milestone billing fields

Revision ID: 9e9404e6376e
Revises: 43d631b0c32d
Create Date: 2026-09-16 13:53:23.740650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e9404e6376e'
down_revision: Union[str, None] = '43d631b0c32d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_updates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.String(length=255), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_role', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('milestone_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'PAID')", name='ck_invoices_status_valid'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('milestones', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('milestones', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))

    # org_id added nullable, backfilled from the parent project, then locked
    # to NOT NULL — not autogenerated, since existing rows have no value yet.
    op.add_column('milestones', sa.Column('org_id', sa.UUID(), nullable=True))
    op.execute(
        "UPDATE milestones SET org_id = projects.org_id "
        "FROM projects WHERE projects.id = milestones.project_id"
    )
    op.alter_column('milestones', 'org_id', nullable=False)
    op.create_foreign_key(
        'fk_milestones_org_id_organizations', 'milestones', 'organizations', ['org_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_milestones_org_id_organizations', 'milestones', type_='foreignkey')
    op.drop_column('milestones', 'org_id')
    op.drop_column('milestones', 'approved_at')
    op.drop_column('milestones', 'amount')
    op.drop_table('invoices')
    op.drop_table('project_updates')
    # ### end Alembic commands ###
