"""add billing frequency, subscription flag, and customer email

Revision ID: ebfb573f672a
Revises: 16446ca0795a
Create Date: 2026-09-22 09:55:32.811014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebfb573f672a'
down_revision: Union[str, None] = '16446ca0795a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('customer_email', sa.String(length=255), nullable=True))
    op.add_column(
        'subscription_plans',
        sa.Column('billing_frequency', sa.String(length=20), nullable=False, server_default='MONTHLY'),
    )
    op.add_column(
        'subscription_plans',
        sa.Column('is_subscription', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('subscription_plans', sa.Column('customer_email', sa.String(length=255), nullable=True))
    op.alter_column('subscription_plans', 'billing_frequency', server_default=None)
    op.alter_column('subscription_plans', 'is_subscription', server_default=None)
    op.alter_column('subscription_plans', 'billing_day',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription_plans', 'billing_day',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('subscription_plans', 'customer_email')
    op.drop_column('subscription_plans', 'is_subscription')
    op.drop_column('subscription_plans', 'billing_frequency')
    op.drop_column('invoices', 'customer_email')
    # ### end Alembic commands ###
